### ISSUE TITLE
Localhost refused to connect

### ISSUE THREAD

**Issue by wilhelmberg** [gorshkov-leonid/mapbox-vector-tiles-chrome-extension#1]
First of all: cool extension, I've been wanting to create something like this myself for ages, but never got to it

Thanks.

But I'm facing a problem, tiles are detected properly

![image](https://user-images.githubusercontent.com/4549888/57177911-7bd9bf00-6e69-11e9-9622-1276d689e57f.png)

but when I click on a tile link I get:

![image](https://user-images.githubusercontent.com/4549888/57177968-06222300-6e6a-11e9-9c60-d55a959e0e8c.png)

At first I thought the link might be missing the port, but it looks ok:
![image](https://user-images.githubusercontent.com/4549888/57177918-96ac3380-6e69-11e9-83ab-f473f890b1ed.png)

I also tested here (https://docs.mapbox.com/vector-tiles/reference/mapbox-streets-v8/) and it worked, so I think the problem might be in my tiles which have JSON strings as properties.

Any ideas?
I can DM you one or two of my tiles if you need them for debugging.

**Comment by gorshkov-leonid** [comment]
I'm afraid the problem is something else. I tried to use the extension with local server
http://localhost:9000/mapbox-tiles/3/2/3.mvt
http://localhost:5000/mapbox-tiles/3/2/3.mvt
and it works. 
I have some ideas:
- blocked port. Could you open this link in new tab? If not, try to change the port or test it on another environment
- request parameters. Maybe request mehod, headers or something else is not matched. It is not 404, but I would check

**Comment by gorshkov-leonid** [comment]
Could you also try extension from zip ( menu -> Tools -> Extensions -> "Load unpacked extension...")
I changed standard browser's way to open via chrome.tabs.create({url: someurl});
[mvt-chrome-plugin.zip](https://github.com/gorshkov-leonid/mapbox-mvt-chrome-extension/files/3144341/mvt-chrome-plugin.zip)

**Comment by wilhelmberg** [comment]
@gorshkov-leonid thanks for your suggestions, but I don't think those are the problems.

* Link works in another tab (right click on the link in your plugin -> `Open link in new tab`).
* Tiles also work with mapboxgljs, leaflet + vectorgrid plugin.
* your updated version now opens a new tab when I click on the link which downloads the tile. But still get the `localhost refused to connect` in the plugin.

Are you sure JSON strings in attributes don't cause any problems?
Any other ideas how I could help debug?

**Comment by wilhelmberg** [comment]
Ah, found the problem:
In my case user has to be authenticated to access tiles.
Somehow the way you try to open/read the tile loses the authentication and server app redirects to login page.

![image](https://user-images.githubusercontent.com/4549888/57181755-0afdcb80-6e98-11e9-9308-76ad0c180202.png)

Any way to pass the authentication cookies as well?

**Comment by gorshkov-leonid** [comment]
I'll try to summarize. When you used the extension from the archive you got this error. Did you get the same error when used an extension from Web Store? I checked that 'Cookie' header is passed in both cases. Could you specify what has not been passed in a request? Think it is some header. Maybe you have some reproducible example, It'll help to make a decision.

**Comment by gorshkov-leonid** [comment]
How to debug as I understand you know. Developer Tools -> Mapbox Vector Tiles -> Right-click -> Inspect -> Console | Sources | Network.

**Comment by wilhelmberg** [comment]
> How to debug as I understand you know. Developer Tools -> Mapbox Vector Tiles -> Right-click -> Inspect -> Console | Sources | Network.

Yeah, thanks. I had figured that out in the meantime - haven't debugged extensions before.

> Did you get the same error when used an extension from Web Store?

Yes, reinstalled from the Web Store just now.

> I checked that 'Cookie' header is passed in both cases.

From what I can tell that's not the case.

### Request when I open the tile url in a new tab (or when it is requested by openlayers, leaftlet, ...):

![image](https://user-images.githubusercontent.com/4549888/57190889-f36a2580-6f1f-11e9-81fa-ebe1c295ca54.png)

### Request when sent from the extension (no cookies, server app serves 302 and redirect to login page):

![image](https://user-images.githubusercontent.com/4549888/57190910-375d2a80-6f20-11e9-87d5-08a305136489.png)

**Comment by wilhelmberg** [comment]
@gorshkov-leonid thanks for your speedy updates.
With the current v1.0.7 it works as expected 😄 🎉

**Comment by gorshkov-leonid** [comment]
Sorry for being late, released and published version 1.0.8.
